### ISSUE TITLE
BUG: Resulting translation files not correct

### ISSUE THREAD

**Issue by timheuer** [IEvangelist/resource-translator#9]
After upgrading to 2.0.2 the files coming back are not correct.  Consider this: 
https://github.com/timheuer/tacticview/pull/8/commits/0c7c1933bc89bb00ec2209e0a60fb95dc09a0516#diff-a8585a8435a28fbd36e66f9b21a54f23c255394e03998cd1bedd5d197e998dbc

This is most definitely not French (it is Finnish).  And the German (de) one came back english.  It's almost as if the first batch is 'off' a bit.  The fr and a few files after that are all still Finnish.

In my debugging I'm pretty sure this:
https://github.com/IEvangelist/resource-translator/blob/main/src/api.ts#L51
needs to be `batchedLocales` instead of batchCount.

But I can't figure out why then it is only getting the last request -- it's definitely issuing an API call, but the resulting translations merged are only the last call.

**Comment by IEvangelist** [comment]
Fixed in this in https://github.com/IEvangelist/resource-translator/commit/068cb0320f42203e41299eccbf4b52ff2c6ccff4, the order in which the results were concatenated together were reversed.

**Comment by timheuer** [comment]
@IEvangelist this is still happening for me.  See run: https://github.com/timheuer/tacticview/runs/1403636993?check_suite_focus=true and resulting PR.  While the groups seem to be translating correctly the final result set has empty arrays resulting in copying the last ones again: https://github.com/timheuer/tacticview/runs/1403636993?check_suite_focus=true#step:3:262

**Comment by IEvangelist** [comment]
I believe that this has since been fixed. There is a new release **v2.1.1** which makes many improvements. The inputs are slightly different, I'd be curious if this is still an issue or not.
